name = "hostkit"
main = ".output/server/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./.output/public"

[observability]
enabled = true

[vars]
# Public vars - safe to commit
VITE_CONVEX_URL = "https://merry-trout-359.convex.cloud"

# Secret vars - add via: wrangler secret put <KEY>
# TWILIO_ACCOUNT_SID
# TWILIO_AUTH_TOKEN
# TWILIO_PHONE_NUMBER
# GEMINI_API_KEY
